### ISSUE TITLE
Dictionary: Color words by status

### ISSUE THREAD

**Issue by matumaros** [pyfection/servare#20]
Color the words differently depending on their current status.
Words with the status "deleted" should not be displayed.

**Comment by pyfection** [comment]
Possible status with their color:
SUG = blue   (when word is first suggested)
EVL = green  (evaluated, when at least one other person has confirmed it)
CFR = black  (confirmed, when a moderator has confirmed it)
RMV = not displayed, filter on frontend, not backend  (removed)

**Comment by pyfection** [comment]
![image](https://user-images.githubusercontent.com/24829389/37553929-5fa05e30-29d1-11e8-9aa1-0f3473db36aa.png)
