### ISSUE TITLE
Add Menu point "Contribute"

### ISSUE THREAD

**Issue by pyfection** [pyfection/servare#82]
This new menu point (when clicked) should display some information about contributing and additionally do either of two things:
- show a page that says that the user needs to have an account (when not logged in)
- show all the available tools to contribute (when logged in)
It also should have a selection of tools as sub-menus

**Comment by hedonazur** [comment]
Hi,
I have two questions. 
So far the available tools are the "Suggest Word" link and the "Random in progress word" link right? 
And. When you said a "selection  of tools as sub-menus" you mean an arrangement like the home site with the Home, News, FAQ and Guest Book ?
